### PR TITLE
introduce cocoapods integration

### PR DESCRIPTION
**Pull request by proger**
Hi,

I converted all of the stuff to CocoaPods to avoid git submodule dances and improve modularity.

I'm not implying for this branch to be merged due to some dirty hacks that still need to be applied (which should probably result in several fixes inside CocoaPods), however I hope you like the concept I'm trying to push.

The branch depends on CocoaPods and my local Pod repository which primarily contain your 3rd party libraries used within this project. Please see the `Makefile` in the root directory.

Running `make prepare all` should yield two buildable workspaces in `Debug Me` and `SuperDebug` directories.

Eager to see your comments.

Cheers,
Vladimir

### CODE REVIEW

**Comment by MonsieurDart** [comment]
I'm not sure this is a good idea, as it is easier to have all the repos locally when working on the Core and the Mac client codes…

**Comment by proger** [comment]
This approach keeps all the files in place — all the repos are kept locally. Is there any problem?

**Comment by MonsieurDart** [comment]
Oh, ok. So CocoaPods is here only for the integration in the Xcode projects, right?

**Comment by proger** [comment]
Yep that's right.

**Comment by MonsieurDart** [comment]
Great then!

To use this in an other iOS app, we have to integrate the SuperDBCore.podspec as a remote pod spec, right?

But it will not be integrated in the CocoaPods/Specs official repo. Therefore it will not be found on the cocoa pods.org website. This is a bit of a pitty. What about adding the SuperDB spec to the official repo?

**Comment by jbrennan** [comment]
@proger Thanks for this pull request. I don't think Cocoapods is a good move at this point. It seems like this setup would make the user jump through more hoops than the submodules technique, at least the way Cocoapods works currently.

Having said that, I really do appreciate your contribution!

**Comment by MonsieurDart** [comment]
@proger Even if Jason thinks integrating CocoaPods into SuperDebug is not a great idea, I personally think that it would be a great thing to have a SuperDebug spec in the official CocoaPods repo. Don't you? It would become really easy to integrate the core into any iPhone app.

I started to do the job but I failed because of an inclusion problem. So I tried yours and I encountered the same compilation problem while "linting" the spec. Do you have this error too:

pod spec lint ~/.cocoapods/master/SuperDebug/0.0.1/SuperDebug.podspec --verbose

(…)

clang: warning: precompiled header '/var/folders/jr/p8dfvmhd1fddrc4hf339j1_80000gp/C/com.apple.Xcode.502/SharedPrecompiledHeaders/Pods-prefix-duzkcmihnfxfijbbevrcbjyrnxvw/Pods-prefix.pch.pth' was ignored because '-include /var/folders/jr/p8dfvmhd1fddrc4hf339j1_80000gp/C/com.apple.Xcode.502/SharedPrecompiledHeaders/Pods-prefix-duzkcmihnfxfijbbevrcbjyrnxvw/Pods-prefix.pch' is not first '-include'

I'm a bit lost in front of this one… And I was wondering if you could have a clue. Thanks in advance.

**Comment by proger** [comment]
@MonsieurDart did `make prepare all` work for you in the first place?

**Comment by nvieirafelipe** [comment]
Hello, I really liked superdb :+1: 
But I was surprised to not find him in cocoapods.

**Comment by MonsieurDart** [comment]
Agreed. Easy and quick integration would be great to have it ready on any project!

I tried to create a pod spec for SuperDB, but failed. I still need to work on that, but I don't have much time for that...

**Comment by jbrennan** [comment]
I've never used Cocoapods before, but I'm curious: do git submodules (the way you use superdb) conflict with Cocoapods?

**Comment by nvieirafelipe** [comment]
No, your project can have libs through the pods and submodules. 

With Cocoapods we could remove steps 2, 3, 4, 5, 6 of the superdb installation. These things would be defined in superdb podspec.

**Comment by jbrennan** [comment]
Ah well. They'll put hair on your chest.

**Pull request closed without merging**
